addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - libdbus-1-dev
      - libx11-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxss-dev
      - libxdg-basedir-dev
      - libglib2.0-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libnotify-dev
      - libgtk-3-dev
      - valgrind
dist: trusty
sudo: false
language: c

before_install:
  - pip install --user cpp-coveralls

script:
  - CFLAGS="-Werror" make all dunstify test-valgrind doc-doxygen
  - make clean
  - CFLAGS="-Werror -fprofile-arcs -ftest-coverage -O0" make test

matrix:
  include:
    - compiler: gcc
      after_success:
        - coveralls --exclude 'test'
    - compiler: clang
      after_success:
        - coveralls --exclude 'test' --gcov llvm-cov --gcov-options gcov
